server_url: https://qtbkf4jg4c.execute-api.eu-central-1.amazonaws.com/beta

custom_server_url: https://qtbkf4jg4c.execute-api.eu-central-1.amazonaws.com/beta

player_name: "Player"

email: "player@csd.uoc.gr"

password: "password"